cache: bundler

rvm:
 - 2.4.10
 - 2.5
 - 2.6
 - 2.7
 - ruby-head

gemfile:
 - Gemfile

before_install: gem update bundler
script: bundle exec rake spec

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
